src/Entity/SP.php
<?php

namespace App\Entity;

use App\Repository\SPRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SPRepository::class)]
class SP
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?float $Price = null;
      
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo = null;

    #[ORM\ManyToOne(inversedBy: 'sPs')]
    private ?Category $cate = null;

    #[ORM\OneToMany(mappedBy: 'item', targetEntity: OrderItem::class)]
    private Collection $orderItems;

    public function __construct()
    {
        $this->orderItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getCate(): ?Category
    {
        return $this->cate;
    }

    public function setCate(?Category $cate): self
    {
        $this->cate = $cate;

        return $this;
    }

    /**
     * @return Collection<int, OrderItem>
     */
    public function getOrderItems(): Collection
    {
        return $this->orderItems;
    }

    public function addOrderItem(OrderItem $orderItem): static
    {
        if (!$this->orderItems->contains($orderItem)) {
            $this->orderItems->add($orderItem);
            $orderItem->setItem($this);
        }

        return $this;
    }

    public function removeOrderItem(OrderItem $orderItem): static
    {
        if ($this->orderItems->removeElement($orderItem)) {
            // set the owning side to null (unless already changed)
            if ($orderItem->getItem() === $this) {
                $orderItem->setItem(null);
            }
        }

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Cart\CartManager;
use App\Entity\SP;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
          
class CartController extends AbstractController
{
    public function __construct(private UrlGeneratorInterface $urlGenerator)
    {
    }
    #[Route('/cart', name: 'app_cart')]
    public function index(Request $request): Response
    {
        $session = $request->getSession();
        $cart_manager = $session->get('cart', new CartManager());
        return $this->render('cart/index.html.twig', [
            "cart_manager"=>$cart_manager
        ]);
    }

    #[Route('/cart/add/{product_id}', name: 'app_cart_add', methods: 'post')]
    public function add(int $product_id, Request $request, EntityManagerInterface $em): Response
    {
        $product = $em->find(SP::class, $product_id);
        $session = $request->getSession();
        $cart_manager = $session->get('cart', new CartManager());
        $cart_manager->addItem($product, 1);
        $session->set('cart', $cart_manager);
        return new RedirectResponse($this->urlGenerator->generate('app_cart'));
    }
    
    #[Route('/cart/remove/{product_id}', name: 'app_cart_remove')]
    public function remove(int $product_id, Request $request, EntityManagerInterface $em): Response
    {
        $product = $em->find(SP::class, $product_id);
        $session = $request->getSession();
        $cart_manager = $session->get('cart', new CartManager());
        $cart_manager->removeItem($product);
        $session->set('cart', $cart_manager);
        return new RedirectResponse($this->urlGenerator->generate('app_cart'));
    }

    #[Route('/cart/update/', name: 'app_cart_update')]
    public function update(Request $request, EntityManagerInterface $em): Response
    {
        $product_id = $request->request->get('product_id');
        $quantity = $request->request->get('qty');
        $product = $em->find(SP::class, $product_id);
        $session = $request->getSession();
        $cart_manager = $session->get('cart', new CartManager());
        $cart_manager->updateItem($product, $quantity);
        $session->set('cart', $cart_manager);
        return new RedirectResponse($this->urlGenerator->generate('app_cart'));
    }
}

templates/cart/index.html.twig
{% extends 'baseuser.html.twig' %}

{% block title %}Cart manager
{% endblock %}

{% block body %}
	<div class="container">
		<a href="{{path('app_products')}}" class="btn btn-primary">Add another product</a>
		<table class="table">
			<tr>
				<th>STT</th>
				<th>Product</th>
				<th>Price</th>
				<th>Quantity</th>
				<th>Total</th>
				<th>Action</th>
			</tr>
			{% for item in cart_manager.items %}
				<tr>
					<form action="{{path('app_cart_update')}}" method="POST">
						<td>{{loop.index}}</td>
						<td>{{item.product.id}}
							-
							{{item.product.name}}</td>
						<td>{{item.product.price}}</td>
						<td>
                            <input type='hidden' value='{{item.product.id}}' name='product_id'/>
							<input type='number' onchange="this.form.submit()" value='{{item.quantity}}' min="1" name='qty'/>
						</td>
						<td>{{item.amount}}</td>
						<td>
							<a href="{{path('app_cart_remove',{'product_id':item.product.id})}}" class="btn btn-warning">Remove</a>
						</td>
 					</form>
				</tr>
			{% endfor %}
			<tr>
				<td colspan='4' class='text-center'>Total Amount</td>
				<td>{{cart_manager.amount}}</td>
			</tr>
		</table>
		<a href="{{path('app_order')}}" class="btn btn-warning">Check out</a>
	</div>
{% endblock %}
{% block javascripts %}
{% endblock %}